config/routes.rb
AutoGay::Application.routes.draw do
  root :to => "home#index"
  get "/map", :to => "home#map"
  get "/about", :to => "home#about"
  get "/target", :to => "home#target"

  resources :violations do
    resource :comments, only: [:create]
  end

  resources :cars
  namespace "api", module: "api" do
    resources :violations, only: [:index, :create, :show ] do
      resource :rates, only: [:create]
      resources :comments, only: [ :create, :index]
    end
    resources :cars
  end

end

app/models/area.rb
#coding: UTF-8
class Area < ActiveRecord::Base
  has_many :car_violations

end

app/models/car.rb
#coding: UTF-8
class Car < ActiveRecord::Base
  has_many :violations

  before_validation :correct_number

  protected

  def correct_number
    number.upcase!
  end
end

app/models/car/violation.rb
class Car::Violation < ActiveRecord::Base
  belongs_to :city
  belongs_to :area
  belongs_to :car
  has_many :comments
  has_attached_file :image,
                    :preserve_files => true,
                    :path => ":rails_root/public/images/:class/:id_:style.:extension",
                    :url => "/images/:class/:id_:style.:extension",
                    :styles => { :medium => "260x180#", :device => "x180" }
  attr_accessor :image_data

  before_validation :decode_image_data,
                    :if => :image_data_provided?


  state_machine :initial => :queried do

    state :queried
    state :new
    state :sent
    state :sent_by_client
    state :solved
    state :closed

    event :completion do
      transition :queried => :new
    end

    event :send_by_server do
      transition :new => :sent
    end

    event :send_by_client do
      transition :new => :send_by_client
    end

    event :solve do
      transition :sent => :solved, :sent_by_client => :solved
    end

    event :close do
      transition :new => :closed
    end

  end

  default_scope order('id DESC')

  def image_url
    img = image.url(:device)
    img[0..img.index('?')-1]
  end

  def judge(is_judge)
    if is_judge
      self.count_bad += 1
    else
      self.count_good +=1
    end
    save
  end

  private

  def image_data_provided?
    !self.image_data.blank?
  end

  def decode_image_data
    data = StringIO.new(Base64.decode64(self.image_data))
    data.class.class_eval { attr_accessor :original_filename, :content_type }
    data.original_filename = "image.png"
    data.content_type = "image/png"
    self.image = data
  end

end

app/models/car/violation/comment.rb
class Car::Violation::Comment < ActiveRecord::Base
  belongs_to :violation

end

app/models/city.rb
#coding: UTF-8
class City < ActiveRecord::Base
  has_many :car_violations

end

app/models/violation.rb
class Violation < ActiveRecord::Base
  belongs_to :car
  has_one :city
  has_attached_file :image

  def image_url
    image.url
  end

end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController

  respond_to :json

end

app/controllers/api/comments_controller.rb
# coding: UTF-8
class Api::CommentsController < Api::ApplicationController
  def create
    violation = Car::Violation.find params[:violation_id]
    comment = Car::Violation::Comment.new :text => params[:post], :violation => violation
    comment.save()
    head :OK
  end
end

app/controllers/api/rates_controller.rb
class Api::RatesController < Api::ApplicationController
  def create
    violation = Car::Violation.find_by_id params[:violation_id]
    if violation
      violation.judge params[:rate] == 'judge'
      head :ok
    else
      head :not_found
    end
  end
end

app/controllers/api/violations_controller.rb
require 'rexml/document'

class Api::ViolationsController < Api::ApplicationController
  def index
    @violations = Car::Violation.limit(10).all
    #.find_by_city_id(:city_id => City.find_by_name(params[:city]).id)
    render :format => :json
  end
  def create
    viol_case = params


    number = viol_case[:number]
    car = Car.find_or_create_by_number :number => number

    violation = Car::Violation.new()

    violation.description = viol_case[:description]
    violation.image_data = viol_case[:image]
    violation.lat = viol_case[:lat]
    violation.long = viol_case[:long]
    violation.address = viol_case[:address]
    violation.save()
    logger.debug violation.image_file_name

    car.violations<< violation

    car.save()

    head :ok
  end
  def show(id)
    render 'views/api/violation/show', Car::Violation.find(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'base'
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def show
    @car = Car.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    violation = Car::Violation.find params[:violation_id]
    comment = Car::Violation::Comment.new :text => params[:comment], :violation => violation
    comment.save()
    render :partial => 'comments/item', :locals => {comment: comment}
  end
end

app/controllers/home_controller.rb
# coding: UTF-8
class HomeController < ApplicationController

  def index
   @violations = Car::Violation.with_state(:new).limit(9).all
  end

  def map
    @violations = Car::Violation.with_state(:new).limit(9).all
    @my_geo_objects = []
    @violations.each do |violation|
      geo_object = {
        geometry: {type: "Point", coordinates: [violation.lat, violation.long]},
        properties: {
        clusterCaption: violation.car.try(:number) || "Нет номера",
        balloonContentBody: violation.description
        }
      }
      @my_geo_objects << geo_object
    end
    @my_geo_objects = @my_geo_objects.to_json
  end

  def about

  end

  def tagret

  end
end

app/controllers/violations_controller.rb
# coding: UTF-8
class ViolationsController < ApplicationController

  def index
   state = params[:state] || :new
   @violations = Car::Violation.with_state(state).paginate(:page => params[:page], :per_page => 9).all
  end

  def show
    @violation = Car::Violation.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/show.html.haml
%h2.number= @car.number
.violations
  = render partial: "violations/list", locals: {violations: @car.violations}

app/views/comments/_item.html.haml
.comment
  .text= comment.text

app/views/home/about.html.haml
%h1 О нас

app/views/home/index.html.haml
.home
  = render partial: "violations/list", locals: {violations: @violations}

app/views/home/map.html.haml
%h1 Карта нарушений
- if @my_geo_objects.present?
  :javascript
    ymaps.ready(function () {
      myGeoObjects = [];
      mgo_json = #{@my_geo_objects}
      var map = new ymaps.Map('map', {center: mgo_json[0]["geometry"]["coordinates"], zoom: 13})
      for(prop in mgo_json) {
        myGeoObjects[prop] = new ymaps.GeoObject(mgo_json[prop]);
          }
    clusterer = new ymaps.Clusterer({clusterDisableClickZoom: true});
    clusterer.add(myGeoObjects);
    map.geoObjects.add(clusterer);
    map.controls.add('mapTools').add("zoomControl");
    });

.map{:id => "map", :style =>"height:500px"}

app/views/home/target.html.haml
%h1 Цель проекта

app/views/layouts/base.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "AutoGay"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") AutoGay
          .container.nav-collapse
            %ul.nav
              %li= link_to "Цель проекта", "/target"
              %li= link_to "Карта нарушений", "/map"
              %li= link_to "О нас", "/about"

    .container

      .content
        .row
          .span9
            = yield
          .span3
            .well.sidebar-nav
              %ul.nav.nav-list
                %li
                  %h3= link_to "Все нарушения", violations_path
              %h3 Мобильное приложение
              .button
                =image_tag "http://mobile.yandex.ru/i/appstore.png"

      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/violations/_item.html.haml
%li.span3
  .thumbnail
    = link_to violation_path(violation) do
      = image_tag violation.image.url(:medium), :size => "260x180"
    .caption{style:"text-align:center;"}
      %h2=violation.car.try(:number) || "Нет номера"
      %p=violation.description
      %p.rating-js
        =link_to "Наказать", api_violation_rates_path(violation), class: "judge btn btn-danger "
        =link_to "Оправдать", api_violation_rates_path(violation), class: "acquit btn btn-success"

app/views/violations/_list.html.haml
%ul.thumbnails
  - violations.each do |violation|
    =render partial: 'violations/item', locals: {violation: violation}

app/views/violations/index.html.haml
.violations
  = render partial: "violations/list", locals: {violations: @violations}
= will_paginate @violations

app/views/violations/show.html.haml
.violation
  .top
    .photo
      =link_to @violation.image.url, :target => 'blank' do
        = image_tag @violation.image.url
    .params
      %h2.description= @violation.description
      .buttons.rating-js
        =link_to "Наказать", api_violation_rates_path(@violation), class: "judge btn btn-big btn-danger "
        =link_to "Оправдать", api_violation_rates_path(@violation), class: "acquit btn btn-big btn-success"

  .bottom
    = link_to @violation.car do
      %h2.number= @violation.car.try(:number) || "Нет номера"
    .address= @violation.address

  .comments
    .add-comment
      %form{id: 'comment', action: violation_comments_path(@violation), method: :POST}
        %label= 'Текст сообщения'
        %textarea{class:'text', name: 'text', cols: 20, rows: 2}
        %a.send.btn
          Отправить
    .comments-list
      - @violation.comments.each do |comment|
        =render partial: 'comments/item', locals: {comment: comment}